
const S=['Chờ xác nhận','Đã xác nhận','Đang chuẩn bị hàng','Đang giao','Đã giao','Hoàn thành'],ALL=[...S,'Đã hủy','Đã hoàn trả'];
const CATS=['Gương LED','Gương phòng tắm','Gương toàn thân','Gương trang trí','Kính cường lực','Kính nội thất'];
const C={'Trắng':'#f1ece4','Đen':'#26231f','Vàng đồng':'#b8864b','Bạc':'#aab3ba','Gỗ sồi':'#a9794c','Trong suốt':'#9fc9d1'};
const $=s=>document.querySelector(s),fmt=n=>(+n||0).toLocaleString('vi-VN')+' ₫',E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const H=s=>{let h=5381;for(const c of s+'lm')h=(h*33^c.charCodeAt(0))>>>0;return h.toString(16)},dt=t=>new Date(t).toLocaleDateString('vi-VN');
function seed(){const P=[['GUONG-LED-001','Gương LED cảm ứng hình chữ nhật',0,2500000,2200000,20,60,80,5,'Trắng','Kính bạc, khung nhôm','rect',1,86,4.8],['GUONG-LED-002','Gương LED tròn viền đèn ấm',0,2900000,0,12,70,70,5,'Đen','Kính bạc, khung thép','round',1,64,4.7],['GUONG-PT-001','Gương phòng tắm chống ẩm viền đen',1,890000,750000,35,50,70,5,'Đen','Kính chống ẩm','rect',0,120,4.5],['GUONG-PT-002','Gương bầu dục phòng tắm treo tường',1,1250000,0,18,60,80,5,'Bạc','Kính bạc, khung inox','round',0,45,4.6],['GUONG-TT-001','Gương toàn thân khung gỗ sồi',2,2100000,1890000,9,50,160,5,'Gỗ sồi','Gỗ sồi, kính bạc','full',0,58,4.9],['GUONG-TT-002','Gương toàn thân khung vàng đồng',2,3200000,0,4,60,170,6,'Vàng đồng','Hợp kim, kính bạc','full',0,31,4.8],['GUONG-TD-001','Gương vòm nghệ thuật phòng khách',3,1980000,0,15,55,110,5,'Vàng đồng','Kính bạc, khung kim loại','arch',0,40,4.7],['GUONG-TD-002','Gương tròn trang trí phòng ngủ',3,1150000,990000,22,60,60,5,'Gỗ sồi','Gỗ, kính bạc','round',0,73,4.4],['KINH-CL-001','Kính cường lực 10mm vách tắm',4,1650000,0,30,90,200,10,'Trong suốt','Kính cường lực','rect',0,52,4.6],['KINH-CL-002','Kính cường lực ốp bếp',4,1350000,1200000,25,70,60,8,'Trong suốt','Kính cường lực','rect',0,67,4.5],['KINH-NT-001','Kính trang trí vân đá',5,2450000,0,3,80,120,8,'Bạc','Kính phủ vân','rect',0,18,4.3],['KINH-NT-002','Vách kính nội thất khung đen',5,4800000,4300000,6,120,220,10,'Đen','Kính cường lực, khung thép','rect',0,22,4.8]];
const now=Date.now(),products=P.map((r,i)=>({id:i+1,code:r[0],name:r[1],cat:CATS[r[2]],price:r[3],sale:r[4],stock:r[5],w:r[6],h:r[7],th:r[8],color:r[9],mat:r[10],shape:r[11],led:r[12],sold:r[13],rating:r[14],status:'Đang bán',ts:now-i*864e5,desc:`${r[1]} kích thước ${r[6]} x ${r[7]} cm, độ dày ${r[8]}mm, chất liệu ${r[10]}. Cắt theo kích thước, lắp đặt tận nơi, bảo hành 12 tháng.`,rv:[]}));
const orders=[...Array(8)].map((_,i)=>{const p=products[(i*3)%12],q=1+i%2;return{id:'DH'+String(i+1).padStart(6,'0'),uid:2,items:[{pid:p.id,name:p.name,price:p.sale||p.price,qty:q}],name:'Nguyễn Văn An',phone:'0912345678',addr:'12 Trần Duy Hưng, Cầu Giấy, Hà Nội',ship:'Giao hàng tiêu chuẩn',pay:'COD',disc:0,total:(p.sale||p.price)*q+30000,status:i==7?'Chờ xác nhận':'Hoàn thành',ts:now-(i%7)*864e5,log:[]}});
return{products,orders,me:0,adm:0,cart:[],cp:'',fav:{},users:[{id:1,name:'Quản trị viên',email:'admin@luminamirror.vn',phone:'0900000000',pw:H('admin123'),role:'ADMIN',lock:0},{id:2,name:'Nguyễn Văn An',email:'khach@example.com',phone:'0912345678',pw:H('123456'),role:'CUSTOMER',lock:0,addr:'12 Trần Duy Hưng, Cầu Giấy, Hà Nội'}],coupons:[{code:'GIAM10',name:'Giảm 10%',type:'pct',val:10,min:1000000,max:100,used:0,end:'2027-12-31',on:1},{code:'GIAM100K',name:'Giảm 100.000đ',type:'amt',val:100000,min:2000000,max:100,used:0,end:'2027-12-31',on:1}]}}
let D;const load=()=>{try{D=JSON.parse(localStorage.getItem('lm_db'))}catch(x){}if(!D)D=seed()};load();
const save=()=>{try{localStorage.setItem('lm_db',JSON.stringify(D))}catch(x){toast('Hết dung lượng lưu trữ, hãy dùng ảnh nhỏ hơn',1)}};
const me=()=>D.users.find(u=>u.id==(MODE=='admin'?D.adm:D.me)&&!u.lock),pr=p=>p.sale||p.price,prod=id=>D.products.find(p=>p.id==id),st=r=>'★'.repeat(Math.round(r))+'☆'.repeat(5-Math.round(r));
const F={q:'',cat:'',max:0,s:'new',pg:1,col:''};let AT='info',MT='dash',AM='login';
function toast(m,bad){const d=document.createElement('div');d.textContent=m;if(bad)d.className='e';$('#ts').append(d);setTimeout(()=>d.remove(),2600)}
function modal(h){$('#md').innerHTML='<div>'+h+'</div>';$('#md').style.display='flex'}const closeM=()=>$('#md').style.display='none';
function ask(m,fn){window._f=fn;modal(`<p>${m}</p><div class=row><button class=d onclick="closeM();_f()">Xác nhận</button><button class=o onclick="closeM()">Hủy</button></div>`)}
const nav=h=>location.hash==h?render():location.hash=h;
function art(p){if(p.img)return`<img src="${p.img}" alt="${E(p.name)}" style="width:100%;height:100%;object-fit:cover">`;const c=C[p.color]||'#aaa',g='g'+p.id,s=p.shape,d=s=='round'?'<circle cx="100" cy="100" r="68"/>':s=='arch'?'<path d="M50 178V92a50 50 0 0 1 100 0v86z"/>':s=='full'?'<rect x="72" y="14" width="56" height="172" rx="3"/>':'<rect x="35" y="35" width="130" height="130" rx="5"/>';
return`<svg viewBox="0 0 200 200" role="img" aria-label="${E(p.name)}"><defs><linearGradient id="${g}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#cfe3ea"/><stop offset=".5" stop-color="#f8fcfd"/><stop offset="1" stop-color="#9dbfcb"/></linearGradient></defs><g fill="url(#${g})" stroke="${c}" stroke-width="7"${p.led?' style="filter:drop-shadow(0 0 8px #ffe3a0)"':''}>${d}</g></svg>`}
const card=p=>{const o=p.sale?Math.round(100-p.sale/p.price*100):0,f=(D.fav[D.me]||[]).includes(p.id);return`<div class=card><a class=ph href="#/p/${p.id}">${art(p)}</a>${o?`<span class=bdg>-${o}%</span>`:''}<button class=hrt aria-label="Yêu thích" onclick="fav(${p.id})">${f?'♥':'♡'}</button><div class=in><h3><a href="#/p/${p.id}">${E(p.name)}</a></h3><div class=row><span class=pr>${fmt(pr(p))}</span>${p.sale?`<span class=old>${fmt(p.price)}</span>`:''}</div><small class=st>${st(p.rating)}</small> <small>${p.stock?'Còn '+p.stock:'<b style="color:var(--bad)">Hết hàng</b>'}</small></div></div>`};
const hdr=()=>{const u=me(),n=D.cart.reduce((s,c)=>s+c.q,0);return`<header><div class="wrap hd"><a class=logo href="#/">◈ Lumina<b>Mirror</b></a><form class=sr onsubmit="F.q=this.q.value;F.pg=1;nav('#/shop');return false"><input name=q placeholder="Tìm tên hoặc mã sản phẩm" value="${E(F.q)}" aria-label="Tìm kiếm"><button>Tìm</button></form><nav><a href="#/shop">Sản phẩm</a><a href="#/${u?'account':'login'}">${u?E(u.name.split(' ').pop()):'Đăng nhập'}</a><a href="#/cart" class=cb>Giỏ <span>${n}</span></a></nav></div><div class=cats>${CATS.map(c=>`<a onclick="setCat('${c}')">${c}</a>`).join('')}</div></header>`};
const ftr=()=>`<footer><div class=wrap><div><h3>Lumina Mirror</h3>Gương, kính và nội thất gương kính cao cấp. Cắt theo kích thước, lắp đặt tận nơi.</div><div><h3>Vận chuyển</h3>Tiêu chuẩn 30.000đ (3–5 ngày), nhanh 60.000đ (1–2 ngày). Đóng gói chống vỡ.</div><div><h3>Đổi trả</h3>Đổi trả trong 7 ngày nếu sản phẩm vỡ, lỗi hoặc sai kích thước.</div><div><h3>Liên hệ</h3>Hotline 0900 000 000<br>lienhe@luminamirror.vn<br>Hà Nội</div></div></footer>`;
const setCat=c=>{F.cat=c;F.pg=1;nav('#/shop')};
function fav(id){const u=me();if(!u){toast('Đăng nhập để dùng yêu thích',1);return nav('#/login')}const a=D.fav[u.id]=D.fav[u.id]||[];a.includes(id)?a.splice(a.indexOf(id),1):a.push(id);save();render()}
function addCart(id,q,buy){const p=prod(id),c=D.cart.find(x=>x.pid==id),n=(c?c.q:0)+q;if(n>p.stock)return toast('Chỉ còn '+p.stock+' sản phẩm trong kho',1);c?c.q=n:D.cart.push({pid:id,q});save();toast('Đã thêm vào giỏ hàng');buy?nav('#/cart'):render()}
const R={};
R.home=()=>{const on=D.products.filter(p=>p.status=='Đang bán'),sec=(t,l)=>`<section class=wrap><h2>${t}</h2><div class=grid>${l.slice(0,4).map(card).join('')}</div></section>`,m=prod(7);
return`<div class=hero onmousemove="this.querySelector('.mir').style.setProperty('--a',(100+event.clientX/innerWidth*60)+'deg')"><div class=wrap><div><h1>Một tấm gương đúng chỗ làm cả căn phòng rộng ra.</h1><p>Gương LED, gương toàn thân, kính cường lực và kính nội thất. Chọn mẫu có sẵn hoặc đặt kích thước riêng.</p><a class=btn href="#/shop">Xem sản phẩm</a></div><div class=mir>${art(m)}</div></div></div><section class="wrap chips">${CATS.map(c=>`<a onclick="setCat('${c}')">${c}</a>`).join('')}</section>`+sec('Đang giảm giá',on.filter(p=>p.sale))+sec('Sản phẩm mới',[...on].sort((a,b)=>b.id-a.id))+sec('Bán chạy nhất',[...on].sort((a,b)=>b.sold-a.sold))};
function shopList(){const q=F.q.toLowerCase(),L=D.products.filter(p=>p.status=='Đang bán'&&(!F.cat||p.cat==F.cat)&&(!F.max||pr(p)<=F.max)&&(!F.col||p.color==F.col)&&(!q||(p.name+p.code).toLowerCase().includes(q)));
const o={asc:(a,b)=>pr(a)-pr(b),desc:(a,b)=>pr(b)-pr(a),new:(a,b)=>b.ts-a.ts,hot:(a,b)=>b.sold-a.sold,rate:(a,b)=>b.rating-a.rating};L.sort(o[F.s]);const n=Math.ceil(L.length/8)||1;F.pg=Math.min(F.pg,n);
if(!L.length)return'<div class=emp><h3>Không tìm thấy sản phẩm</h3><p>Thử bỏ bớt bộ lọc hoặc đổi từ khóa.</p><button onclick="F.q=F.cat=F.col=\'\';F.max=0;render()">Xóa bộ lọc</button></div>';
return`<div class=grid>${L.slice((F.pg-1)*8,F.pg*8).map(card).join('')}</div><div class=row style="justify-content:center;margin-top:20px">${[...Array(n)].map((_,i)=>`<button class="s ${i+1==F.pg?'':'o'}" onclick="F.pg=${i+1};$('#list').innerHTML=shopList()">${i+1}</button>`).join('')}</div>`}
const fl=(k,v)=>{F[k]=v;F.pg=1;$('#list').innerHTML=shopList()};
R.shop=()=>`<div class=wrap><div class=bc><a href="#/">Trang chủ</a> / Sản phẩm${F.cat?' / '+F.cat:''}</div><div class=tb><select onchange="fl('cat',this.value)" aria-label="Danh mục"><option value="">Tất cả danh mục</option>${CATS.map(c=>`<option ${c==F.cat?'selected':''}>${c}</option>`)}</select><select onchange="fl('max',+this.value)" aria-label="Giá"><option value=0>Mọi mức giá</option>${[[1000000,'Dưới 1 triệu'],[2500000,'Dưới 2,5 triệu'],[5000000,'Dưới 5 triệu']].map(x=>`<option value=${x[0]} ${x[0]==F.max?'selected':''}>${x[1]}</option>`)}</select><select onchange="fl('col',this.value)" aria-label="Màu"><option value="">Mọi màu</option>${Object.keys(C).map(c=>`<option ${c==F.col?'selected':''}>${c}</option>`)}</select><select onchange="fl('s',this.value)" aria-label="Sắp xếp">${[['new','Mới nhất'],['asc','Giá thấp → cao'],['desc','Giá cao → thấp'],['hot','Bán chạy nhất'],['rate','Đánh giá cao nhất']].map(x=>`<option value=${x[0]} ${x[0]==F.s?'selected':''}>${x[1]}</option>`)}</select></div><div id=list>${shopList()}</div></div>`;
R.p=id=>{const p=prod(id);if(!p)return R.nf();const u=me(),o=p.sale?Math.round(100-p.sale/p.price*100):0,av=p.rv.length?p.rv.reduce((s,r)=>s+r.s,0)/p.rv.length:p.rating,can=u&&D.orders.some(x=>x.uid==u.id&&x.status=='Hoàn thành'&&x.items.some(i=>i.pid==p.id)),rel=D.products.filter(x=>x.cat==p.cat&&x.id!=p.id&&x.status=='Đang bán').slice(0,4);
return`<div class=wrap><div class=bc><a href="#/">Trang chủ</a> / <a onclick="setCat('${p.cat}')">${p.cat}</a> / ${E(p.name)}</div><div class=two><div class="card ph" style="border-radius:12px">${art(p)}</div><div><h1 style="font-size:30px">${E(p.name)}</h1><p class=bc>Mã: ${p.code} · <span class=st>${st(av)}</span> ${av.toFixed(1)} (${p.rv.length} đánh giá)</p><div class=row><b class=pr style="font-size:26px">${fmt(pr(p))}</b>${p.sale?`<span class=old>${fmt(p.price)}</span><span class="tag g">-${o}%</span>`:''}</div><p>${E(p.desc)}</p><table><tr><th>Kích thước</th><td>${p.w} x ${p.h} cm</td></tr><tr><th>Độ dày</th><td>${p.th} mm</td></tr><tr><th>Màu sắc</th><td>${p.color}</td></tr><tr><th>Chất liệu</th><td>${E(p.mat)}</td></tr><tr><th>Tình trạng</th><td>${p.stock?(p.stock<=5?'Sắp hết hàng (còn '+p.stock+')':'Còn '+p.stock+' sản phẩm'):'Hết hàng'}</td></tr></table><div class=row style="margin-top:14px"><input id=qt type=number min=1 max=${p.stock} value=1 style="width:80px" aria-label="Số lượng"><button ${p.stock?'':'disabled'} onclick="addCart(${p.id},Math.max(1,+$('#qt').value||1))">Thêm vào giỏ</button><button class=o ${p.stock?'':'disabled'} onclick="addCart(${p.id},Math.max(1,+$('#qt').value||1),1)">Mua ngay</button><button class=o onclick="fav(${p.id})">${(D.fav[D.me]||[]).includes(p.id)?'♥ Đã thích':'♡ Yêu thích'}</button></div></div></div><section><h2>Đánh giá</h2>${p.rv.map(r=>`<div class=box style="margin-bottom:8px"><b>${E(r.u)}</b> <span class=st>${st(r.s)}</span><br>${E(r.t)}</div>`).join('')||'<p class=emp>Chưa có đánh giá.</p>'}${can?`<form class=box onsubmit="return rate(${p.id},this)"><label>Số sao<select name=s>${[5,4,3,2,1].map(n=>`<option>${n}</option>`)}</select></label><label>Nội dung<textarea name=t required></textarea></label><button>Gửi đánh giá</button></form>`:'<small>Chỉ khách đã nhận hàng mới đánh giá được.</small>'}</section>${rel.length?`<section><h2>Sản phẩm liên quan</h2><div class=grid>${rel.map(card).join('')}</div></section>`:''}</div>`};
function rate(id,f){prod(id).rv.push({u:me().name,s:+f.s.value,t:f.t.value});save();toast('Cảm ơn bạn đã đánh giá');render();return false}
const rows=()=>D.cart.map(c=>({p:prod(c.pid),q:c.q})).filter(r=>r.p),sub=()=>rows().reduce((s,r)=>s+pr(r.p)*r.q,0);
function disc(){const c=D.coupons.find(x=>x.code==D.cp&&x.on&&x.used<x.max&&new Date(x.end)>=new Date()),s=sub();return c&&s>=c.min?Math.min(s,c.type=='pct'?Math.round(s*c.val/100):c.val):0}
function qty(id,d){const c=D.cart.find(x=>x.pid==id),p=prod(id);if(c.q+d>p.stock)return toast('Vượt quá tồn kho',1);c.q+=d;if(c.q<1)D.cart=D.cart.filter(x=>x!==c);save();render()}
const delc=id=>ask('Xóa sản phẩm khỏi giỏ hàng?',()=>{D.cart=D.cart.filter(x=>x.pid!=id);save();render()});
function coupon(v){const c=D.coupons.find(x=>x.code==v.trim().toUpperCase());if(!c||!c.on)toast('Mã giảm giá không hợp lệ',1);else if(sub()<c.min)toast('Đơn tối thiểu '+fmt(c.min),1);else{D.cp=c.code;save();toast('Đã áp dụng '+c.name)}render()}
R.cart=()=>{const r=rows();if(!r.length)return'<div class=wrap><div class=emp><h2>Giỏ hàng trống</h2><a class=btn href="#/shop">Tiếp tục mua sắm</a></div></div>';const d=disc();
return`<div class=wrap><h2 style="margin-top:20px">Giỏ hàng</h2><div class=tw><table><tr><th>Sản phẩm</th><th>Đơn giá</th><th>Số lượng</th><th>Thành tiền</th><th></th></tr>${r.map(x=>`<tr><td>${E(x.p.name)}</td><td>${fmt(pr(x.p))}</td><td><div class=row><button class="s o" onclick="qty(${x.p.id},-1)">−</button>${x.q}<button class="s o" onclick="qty(${x.p.id},1)">+</button></div></td><td>${fmt(pr(x.p)*x.q)}</td><td><button class="s d" onclick="delc(${x.p.id})">Xóa</button></td></tr>`).join('')}</table></div><div class=two style="margin-top:16px"><div class=box><label>Mã giảm giá (thử GIAM10 hoặc GIAM100K)</label><div class=row><input id=cpn value="${E(D.cp)}" style="flex:1"><button onclick="coupon($('#cpn').value)">Áp dụng</button></div><br><button class=o onclick="ask('Xóa toàn bộ giỏ hàng?',()=>{D.cart=[];save();render()})">Xóa toàn bộ giỏ</button></div><div class=box><p class=row style="justify-content:space-between">Tạm tính <b>${fmt(sub())}</b></p><p class=row style="justify-content:space-between">Giảm giá <b>-${fmt(d)}</b></p><p class=row style="justify-content:space-between">Phí vận chuyển <small>tính ở bước thanh toán</small></p><h3 class=row style="justify-content:space-between">Tổng <span class=pr>${fmt(sub()-d)}</span></h3><br><a class=btn href="#/checkout">Đặt hàng</a></div></div></div>`};
R.checkout=()=>{const u=me();if(!u){toast('Vui lòng đăng nhập để đặt hàng',1);setTimeout(()=>nav('#/login'));return''}if(!rows().length)return R.cart();const i=(k,l,v='',t='text')=>`<label>${l}<input name=${k} type=${t} value="${E(v)}" ${k=='note'?'':'required'}></label>`;
return`<div class=wrap><h2 style="margin-top:20px">Thanh toán</h2><form class=two onsubmit="return order(this)"><div class=box><div class=fg>${i('name','Họ tên',u.name)}${i('phone','Số điện thoại',u.phone)}</div>${i('email','Email',u.email,'email')}${i('addr','Địa chỉ',u.addr)}<div class=fg>${i('city','Tỉnh/thành phố')}${i('dist','Quận/huyện')}</div>${i('ward','Phường/xã')}${i('note','Ghi chú')}</div><div class=box><label>Giao hàng<select name=ship onchange="$('#tot').textContent=fmt(${sub()-disc()}+(this.value[0]=='N'?60000:30000))"><option value="Giao hàng tiêu chuẩn">Tiêu chuẩn – 30.000 ₫</option><option value="Nhanh">Nhanh – 60.000 ₫</option></select></label><label>Thanh toán<select name=pay><option>COD</option><option>Chuyển khoản ngân hàng</option><option>Thanh toán online</option></select></label><p><small>Chuyển khoản/online: bản demo ghi nhận phương thức, chưa nối cổng thanh toán thật.</small></p>${rows().map(x=>`<p class=row style="justify-content:space-between"><span>${E(x.p.name)} ×${x.q}</span>${fmt(pr(x.p)*x.q)}</p>`).join('')}<p class=row style="justify-content:space-between">Giảm giá<b>-${fmt(disc())}</b></p><h3 class=row style="justify-content:space-between">Tổng <span class=pr id=tot>${fmt(sub()-disc()+30000)}</span></h3><br><button>Xác nhận đặt hàng</button></div></form></div>`};
function order(f){const v=Object.fromEntries(new FormData(f)),r=rows();if(!/^0\d{9}$/.test(v.phone)){toast('Số điện thoại không hợp lệ',1);return false}
for(const x of r)if(x.q>x.p.stock){toast(x.p.name+' không đủ hàng',1);return false}
const d=disc(),sh=v.ship[0]=='N'?60000:30000,id='DH'+String(D.orders.length+1).padStart(6,'0');
D.orders.push({id,uid:D.me,items:r.map(x=>({pid:x.p.id,name:x.p.name,price:pr(x.p),qty:x.q})),name:v.name,phone:v.phone,addr:[v.addr,v.ward,v.dist,v.city].filter(Boolean).join(', '),note:v.note,ship:v.ship,pay:v.pay,disc:d,total:sub()-d+sh,status:'Chờ xác nhận',ts:Date.now(),log:[['Chờ xác nhận',Date.now()]]});
r.forEach(x=>{x.p.stock-=x.q;x.p.sold+=x.q});const c=D.coupons.find(x=>x.code==D.cp);if(c&&d)c.used++;D.cart=[];D.cp='';save();nav('#/done/'+id);return false}
R.done=id=>{const o=D.orders.find(x=>x.id==id);return o?`<div class=wrap><div class=emp><h2 style="color:var(--ok)">Đặt hàng thành công</h2><p>Mã đơn hàng: <b>${o.id}</b><br>Tổng tiền: <b>${fmt(o.total)}</b></p><a class=btn href="#/account">Theo dõi đơn hàng</a></div></div>`:R.nf()};
R.login=()=>{if(me())return setTimeout(()=>nav('#/account')),'';const r=AM=='reg',i=(k,l,t='text')=>`<label>${l}<input name=${k} type=${t} required></label>`;
return`<div class=wrap style="max-width:420px"><h2 style="margin-top:30px">${r?'Tạo tài khoản':'Đăng nhập'}</h2><form class=box onsubmit="return auth(this)">${r?i('name','Họ tên')+i('phone','Số điện thoại'):''}${i('email','Email','email')}${i('pw','Mật khẩu (tối thiểu 6 ký tự)','password')}${r?i('pw2','Xác nhận mật khẩu','password'):''}<button>${r?'Đăng ký':'Đăng nhập'}</button> <a onclick="AM='${r?'login':'reg'}';render()" style="color:var(--acc)">${r?'Đã có tài khoản?':'Chưa có tài khoản?'}</a><p><small>Demo: khach@example.com / 123456</small></p></form></div>`};
function auth(f){const v=Object.fromEntries(new FormData(f)),em=v.email.toLowerCase();
if(AM=='reg'){if(v.pw.length<6||v.pw!=v.pw2||!/^0\d{9}$/.test(v.phone)){toast('Kiểm tra lại SĐT và mật khẩu (≥6 ký tự, trùng khớp)',1);return false}if(D.users.some(u=>u.email==em)){toast('Email đã được đăng ký',1);return false}
const u={id:Date.now(),name:v.name,email:em,phone:v.phone,pw:H(v.pw),role:'CUSTOMER',lock:0};D.users.push(u);D.me=u.id;toast('Đăng ký thành công')}
else{const u=D.users.find(x=>x.email==em&&x.pw==H(v.pw));if(!u){toast('Sai email hoặc mật khẩu',1);return false}if(u.lock){toast('Tài khoản đã bị khóa',1);return false}if(MODE=='admin'){if(u.role!='ADMIN'){toast('Đây không phải tài khoản quản trị',1);return false}D.adm=u.id}else{if(u.role=='ADMIN'){toast('Quản trị viên vui lòng đăng nhập tại trang admin.html',1);return false}D.me=u.id}}
save();MODE=='admin'?render():nav('#/account');return false}
const logout=()=>{if(MODE=='admin'){D.adm=0;save();render()}else{D.me=0;save();nav('#/')}};
R.account=()=>{const u=me();if(!u)return setTimeout(()=>nav('#/login')),'';const my=D.orders.filter(o=>o.uid==u.id).reverse(),tb=(k,l)=>`<button class="${AT==k?'on':''}" onclick="AT='${k}';render()">${l}</button>`;let b='';
if(AT=='info')b=`<form class=box onsubmit="return prof(this)"><div class=fg><label>Họ tên<input name=name value="${E(u.name)}" required></label><label>Số điện thoại<input name=phone value="${E(u.phone)}"></label></div><label>Email<input value="${E(u.email)}" disabled></label><label>Ngày sinh<input type=date name=dob value="${E(u.dob)}"></label><label>Địa chỉ mặc định<input name=addr value="${E(u.addr)}"></label><button>Lưu thông tin</button></form>`;
else if(AT=='ord')b=my.map(o=>`<div class=box style="margin-bottom:10px"><div class=row style="justify-content:space-between"><b>${o.id}</b><span>${dt(o.ts)}</span><span class="tag ${o.status=='Hoàn thành'?'g':o.status=='Đã hủy'?'r':''}">${o.status}</span><b>${fmt(o.total)}</b></div><small>${o.items.map(i=>E(i.name)+' ×'+i.qty).join(', ')}<br>${o.pay} · ${E(o.addr)}</small>${o.status=='Chờ xác nhận'?`<br><button class="s d" onclick="ask('Hủy đơn ${o.id}?',()=>setSt('${o.id}','Đã hủy'))">Hủy đơn</button>`:''}</div>`).join('')||'<div class=emp>Bạn chưa có đơn hàng.</div>';
else b=(D.fav[u.id]||[]).length?`<div class=grid>${D.fav[u.id].map(prod).filter(Boolean).map(card).join('')}</div>`:'<div class=emp>Chưa có sản phẩm yêu thích.</div>';
return`<div class=wrap><div class=row style="justify-content:space-between;margin-top:20px"><h2>Xin chào, ${E(u.name)}</h2><button class=o onclick="logout()">Đăng xuất</button></div><div class=tabs>${tb('info','Thông tin')}${tb('ord','Đơn hàng')}${tb('fav','Yêu thích')}</div>${b}</div>`};
function prof(f){Object.assign(me(),Object.fromEntries(new FormData(f)));save();toast('Đã lưu thông tin');render();return false}
function setSt(id,s){const o=D.orders.find(x=>x.id==id);if(s=='Đã hủy'&&o.status!='Đã hủy')o.items.forEach(i=>{const p=prod(i.pid);if(p)p.stock+=i.qty});(o.log=o.log||[]).push([s,Date.now()]);o.status=s;save();toast('Đã cập nhật: '+s);render()}
const rev=()=>D.orders.filter(o=>!['Đã hủy','Đã hoàn trả'].includes(o.status));
R.admin=()=>{const u=me();if(!u||u.role!='ADMIN')return admLogin();
const tb=(k,l)=>`<button class="${MT==k?'on':''}" onclick="MT='${k}';render()">${l}</button>`,tabs=`<div class=tabs>${tb('dash','Tổng quan')}${tb('st','Thống kê')}${tb('prod','Sản phẩm')}${tb('ord','Đơn hàng')}${tb('usr','Khách hàng')}${tb('cp','Mã giảm giá')}</div>`;let b='';
if(MT=='dash'){const R_=rev(),days=[...Array(7)].map((_,i)=>{const t=new Date(Date.now()-(6-i)*864e5).toDateString();return[new Date(t).getDate()+'/'+(new Date(t).getMonth()+1),R_.filter(o=>new Date(o.ts).toDateString()==t).reduce((s,o)=>s+o.total,0)]}),mx=Math.max(...days.map(d=>d[1]),1),low=D.products.filter(p=>p.stock<=5),top=[...D.products].sort((a,b)=>b.sold-a.sold).slice(0,5);
b=`<div class=stat><div>Doanh thu<b>${fmt(R_.reduce((s,o)=>s+o.total,0))}</b></div><div>Đơn hàng<b>${D.orders.length}</b></div><div>Khách hàng<b>${D.users.filter(x=>x.role=='CUSTOMER').length}</b></div><div>Sản phẩm<b>${D.products.length}</b></div><div>Đơn chờ xử lý<b>${D.orders.filter(o=>o.status=='Chờ xác nhận').length}</b></div><div>Sắp hết hàng<b>${low.length}</b></div></div><div class=two style="margin-top:16px"><div class=box><h3>Doanh thu 7 ngày</h3><svg viewBox="0 0 280 140" style="width:100%">${days.map((d,i)=>`<rect x="${i*40+8}" y="${110-d[1]/mx*100}" width="26" height="${d[1]/mx*100}" fill="var(--acc)" rx="3"><title>${fmt(d[1])}</title></rect><text x="${i*40+21}" y="128" font-size="10" text-anchor="middle" fill="var(--mut)">${d[0]}</text>`).join('')}</svg></div><div class=box><h3>Bán chạy</h3>${top.map(p=>`<p class=row style="justify-content:space-between;margin:6px 0"><span>${E(p.name)}</span><b>${p.sold}</b></p>`).join('')}<h3 style="margin-top:12px">Cảnh báo tồn kho</h3>${low.map(p=>`<p style="margin:4px 0">${E(p.name)}: <span class="tag ${p.stock?'':'r'}">${p.stock?'Còn '+p.stock:'Hết hàng'}</span></p>`).join('')||'Ổn định'}</div></div>`}
else if(MT=='prod'){const q=(window.AQ||'').toLowerCase(),L=D.products.filter(p=>(p.name+p.code).toLowerCase().includes(q));b=`<div class=row style="margin-bottom:10px"><input placeholder="Tìm sản phẩm" value="${E(window.AQ)}" oninput="AQ=this.value;clearTimeout(window._t);window._t=setTimeout(()=>{render();const i=document.querySelector('[placeholder=\\'Tìm sản phẩm\\']');i.focus();i.setSelectionRange(99,99)},300)" style="flex:1"><button onclick="pForm(0)">+ Thêm sản phẩm</button></div><div class=tw><table><tr><th>Mã</th><th>Tên</th><th>Danh mục</th><th>Giá</th><th>Kho</th><th>Trạng thái</th><th></th></tr>${L.map(p=>`<tr><td>${p.code}</td><td>${E(p.name)}</td><td>${p.cat}</td><td>${fmt(p.price)}${p.sale?'<br><small class=pr>'+fmt(p.sale)+'</small>':''}</td><td>${p.stock}</td><td><span class="tag ${p.status=='Đang bán'?'g':''}">${p.status}</span></td><td class=row><button class="s o" onclick="pForm(${p.id})">Sửa</button><button class="s d" onclick="ask('Xóa sản phẩm này?',()=>{D.products=D.products.filter(x=>x.id!=${p.id});save();render()})">Xóa</button></td></tr>`).join('')}</table></div>`}
else if(MT=='ord')b=ordTab();else if(MT=='st')b=statTab();
else if(MT=='usr')b=`<div class=tw><table><tr><th>Tên</th><th>Email</th><th>SĐT</th><th>Vai trò</th><th>Đơn</th><th></th></tr>${D.users.map(x=>`<tr><td>${E(x.name)}</td><td>${E(x.email)}</td><td>${E(x.phone)}</td><td>${x.role}</td><td>${D.orders.filter(o=>o.uid==x.id).length}</td><td>${x.id==D.adm?'':`<button class="s ${x.lock?'':'d'}" onclick="x_=${x.id};D.users.find(u=>u.id==x_).lock^=1;save();render()">${x.lock?'Mở khóa':'Khóa'}</button>`}</td></tr>`).join('')}</table></div>`;
else b=`<div class=tw><table><tr><th>Mã</th><th>Chương trình</th><th>Giá trị</th><th>Tối thiểu</th><th>Đã dùng</th><th>Hạn</th><th></th></tr>${D.coupons.map((c,i)=>`<tr><td>${c.code}</td><td>${E(c.name)}</td><td>${c.type=='pct'?c.val+'%':fmt(c.val)}</td><td>${fmt(c.min)}</td><td>${c.used}/${c.max}</td><td>${c.end}</td><td><button class="s ${c.on?'d':''}" onclick="D.coupons[${i}].on^=1;save();render()">${c.on?'Tắt':'Bật'}</button></td></tr>`).join('')}</table></div><form class=box style="margin-top:12px" onsubmit="return addCp(this)"><div class=fg><label>Mã<input name=code required></label><label>Tên<input name=name required></label><label>Loại<select name=type><option value=pct>Phần trăm</option><option value=amt>Số tiền</option></select></label><label>Giá trị<input name=val type=number min=1 required></label><label>Đơn tối thiểu<input name=min type=number min=0 value=0></label><label>Số lần dùng<input name=max type=number min=1 value=100></label></div><label>Ngày kết thúc<input name=end type=date required></label><button>Thêm mã</button></form>`;
return`<div class=wrap><h2 style="margin-top:20px">Trang quản trị</h2>${tabs}${b}</div>`};
function addCp(f){const v=Object.fromEntries(new FormData(f));v.code=v.code.toUpperCase();if(D.coupons.some(c=>c.code==v.code)){toast('Mã đã tồn tại',1);return false}D.coupons.push({...v,val:+v.val,min:+v.min,max:+v.max,used:0,on:1});save();render();return false}
function pForm(id){const p=D.products.find(x=>x.id==id)||{code:'',name:'',cat:CATS[0],price:'',sale:0,stock:10,w:60,h:80,th:5,color:'Trắng',mat:'',shape:'rect',led:0,status:'Đang bán',desc:''},
i=(k,l,t='text')=>`<label>${l}<input name=${k} type=${t} value="${E(p[k])}" ${t=='number'?'min=0':''}></label>`,s=(k,l,o)=>`<label>${l}<select name=${k}>${o.map(x=>`<option ${x==p[k]?'selected':''}>${x}</option>`).join('')}</select></label>`;
modal(`<h3>${id?'Sửa':'Thêm'} sản phẩm</h3><form onsubmit="return saveP(${id},this)"><div class=fg>${i('code','Mã sản phẩm')}${i('name','Tên sản phẩm')}${s('cat','Danh mục',CATS)}${s('status','Trạng thái',['Đang bán','Ngừng bán'])}${i('price','Giá bán','number')}${i('sale','Giá khuyến mãi (0 = không)','number')}${i('stock','Tồn kho','number')}${s('color','Màu sắc',Object.keys(C))}${i('w','Rộng (cm)','number')}${i('h','Cao (cm)','number')}${i('th','Độ dày (mm)','number')}${s('shape','Kiểu dáng',['rect','round','arch','full'])}</div>${i('mat','Chất liệu')}<label>Ảnh sản phẩm (tùy chọn)<input type=file accept="image/*" onchange="upImg(this)"></label><input type=hidden name=img id=imgv value="${E(p.img||'')}"><label>Mô tả<textarea name=desc>${E(p.desc)}</textarea></label><label><input type=checkbox name=led style="width:auto" ${p.led?'checked':''}> Có đèn LED</label><div class=row><button>Lưu</button><button type=button class=o onclick="closeM()">Hủy</button></div></form>`)}
function saveP(id,f){const v=Object.fromEntries(new FormData(f));['price','sale','stock','w','h','th'].forEach(k=>v[k]=+v[k]||0);v.led=v.led?1:0;
if(!v.code||!v.name||v.price<=0){toast('Nhập mã, tên và giá bán > 0',1);return false}if(v.sale&&v.sale>=v.price){toast('Giá khuyến mãi phải nhỏ hơn giá bán',1);return false}
if(D.products.some(p=>p.code==v.code&&p.id!=id)){toast('Mã sản phẩm đã tồn tại',1);return false}
if(id)Object.assign(prod(id),v);else D.products.push({...v,id:Date.now(),sold:0,rating:5,ts:Date.now(),rv:[]});save();closeM();toast('Đã lưu sản phẩm');render();return false}
R.nf=()=>'<div class=wrap><div class=emp><h2>404 – Không tìm thấy trang</h2><a class=btn href="#/">Về trang chủ</a></div></div>';
function render(){try{if(MODE=='admin'){$('#app').innerHTML=admHdr()+'<main>'+R.admin()+'</main>';return}const[h,a]=(location.hash||'#/').slice(2).split('/'),f=R[h||'home']||R.nf;$('#app').innerHTML=hdr()+'<main>'+f(a)+'</main>'+(h=='admin'?'':ftr())}catch(x){$('#app').innerHTML='<div class=emp><h2>Có lỗi hệ thống</h2><p>Vui lòng tải lại trang.</p></div>'}}

let OF={st:'',q:''},ST={r:'7',a:'',b:''};
const admHdr=()=>`<header><div class="wrap hd"><a class=logo>◈ Lumina<b>Admin</b></a><nav><a href="index.html">Xem cửa hàng</a>${me()?'<button class=o onclick="logout()">Đăng xuất</button>':''}</nav></div></header>`;
const admLogin=()=>`<div class=wrap style="max-width:400px"><h2 style="margin-top:40px">Đăng nhập quản trị</h2><form class=box onsubmit="AM='login';return auth(this)"><label>Email<input name=email type=email required></label><label>Mật khẩu<input name=pw type=password required></label><button>Đăng nhập</button></form></div>`;
const ordTab=()=>{const q=OF.q.toLowerCase(),L=[...D.orders].reverse().filter(o=>(!OF.st||o.status==OF.st)&&(!q||(o.id+o.name+o.phone).toLowerCase().includes(q)));
return`<div class=row style="margin-bottom:10px"><input placeholder="Tìm mã đơn, tên, SĐT" value="${E(OF.q)}" onchange="OF.q=this.value;render()" style="flex:1"><select onchange="OF.st=this.value;render()" style="width:auto"><option value="">Tất cả (${D.orders.length})</option>${ALL.map(s=>`<option value="${s}" ${s==OF.st?'selected':''}>${s} (${D.orders.filter(o=>o.status==s).length})</option>`)}</select></div><div class=tw><table><tr><th>Mã</th><th>Khách hàng</th><th>SĐT</th><th>Ngày</th><th>Tổng</th><th>Thanh toán</th><th>Trạng thái</th><th></th></tr>${L.map(o=>`<tr><td>${o.id}</td><td>${E(o.name)}</td><td>${E(o.phone)}</td><td>${dt(o.ts)}</td><td>${fmt(o.total)}</td><td>${o.pay}</td><td><select onchange="setSt('${o.id}',this.value)">${ALL.map(s=>`<option ${s==o.status?'selected':''}>${s}</option>`)}</select></td><td><button class="s o" onclick="ordView('${o.id}')">Chi tiết</button></td></tr>`).join('')||'<tr><td colspan=8>Không có đơn hàng</td></tr>'}</table></div>`};
function ordView(id){const o=D.orders.find(x=>x.id==id),i=S.indexOf(o.status),nx=i>=0&&i<5?S[i+1]:'';
modal(`<h3>Đơn ${o.id}</h3><p>${E(o.name)} · ${E(o.phone)}<br>${E(o.addr)}${o.note?'<br>Ghi chú: '+E(o.note):''}<br>${E(o.ship)} · ${o.pay} · ${new Date(o.ts).toLocaleString('vi-VN')}</p><table>${o.items.map(t=>`<tr><td>${E(t.name)}</td><td>×${t.qty}</td><td>${fmt(t.price*t.qty)}</td></tr>`).join('')}<tr><td colspan=2>Giảm giá</td><td>-${fmt(o.disc)}</td></tr><tr><th colspan=2>Tổng</th><th>${fmt(o.total)}</th></tr></table><p><b>${o.status}</b><br><small>${(o.log||[]).map(l=>l[0]+' – '+new Date(l[1]).toLocaleString('vi-VN')).join('<br>')}</small></p><div class=row>${nx?`<button onclick="closeM();setSt('${o.id}','${nx}')">Chuyển sang: ${nx}</button>`:''}${i>=0&&i<4?`<button class=d onclick="closeM();setSt('${o.id}','Đã hủy')">Hủy đơn</button>`:''}<button class=o onclick="closeM()">Đóng</button></div>`)}
function statRange(){const d=new Date(),t=new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime(),r=ST.r;return r=='0'?[t,t+864e5]:r=='7'?[t-6*864e5,t+864e5]:r=='m'?[new Date(d.getFullYear(),d.getMonth(),1).getTime(),t+864e5]:r=='y'?[new Date(d.getFullYear(),0,1).getTime(),t+864e5]:[ST.a?new Date(ST.a).getTime():0,ST.b?new Date(ST.b).getTime()+864e5:t+864e5]}
function statTab(){const[a,b]=statRange(),L=D.orders.filter(o=>o.ts>=a&&o.ts<b),ok=L.filter(o=>!['Đã hủy','Đã hoàn trả'].includes(o.status)),sum=l=>l.reduce((s,o)=>s+o.total,0),cnt=s=>L.filter(o=>o.status==s).length,bc={},bp={},bd={};
ok.forEach(o=>{bd[dt(o.ts)]=(bd[dt(o.ts)]||0)+o.total;o.items.forEach(i=>{const p=prod(i.pid),c=p?p.cat:'Khác';bc[c]=(bc[c]||0)+i.price*i.qty;bp[i.name]=(bp[i.name]||0)+i.qty})});
const tb=(o,f)=>Object.entries(o).sort((x,y)=>y[1]-x[1]).map(([k,v])=>`<tr><td>${E(k)}</td><td>${f(v)}</td></tr>`).join('')||'<tr><td>Chưa có dữ liệu</td></tr>',slow=[...D.products].sort((x,y)=>x.sold-y.sold).slice(0,5),out=D.products.filter(p=>p.stock<=5);
return`<div class="row nop" style="margin-bottom:12px"><select onchange="ST.r=this.value;render()" style="width:auto">${[['0','Hôm nay'],['7','7 ngày qua'],['m','Tháng này'],['y','Năm nay'],['c','Tùy chọn']].map(x=>`<option value=${x[0]} ${x[0]==ST.r?'selected':''}>${x[1]}</option>`)}</select>${ST.r=='c'?`<input type=date value="${ST.a}" onchange="ST.a=this.value;render()" style="width:auto"> – <input type=date value="${ST.b}" onchange="ST.b=this.value;render()" style="width:auto">`:''}<button class=o onclick="csv()">Xuất Excel (CSV)</button><button class=o onclick="print()">In / lưu PDF</button></div>
<div class=stat><div>Doanh thu<b>${fmt(sum(ok))}</b></div><div>Tổng đơn<b>${L.length}</b></div><div>Thành công<b>${cnt('Hoàn thành')}</b></div><div>Đang xử lý<b>${L.filter(o=>S.slice(0,5).includes(o.status)).length}</b></div><div>Đã hủy<b>${cnt('Đã hủy')}</b></div><div>Hoàn trả<b>${cnt('Đã hoàn trả')}</b></div><div>Trung bình/đơn<b>${fmt(ok.length?Math.round(sum(ok)/ok.length):0)}</b></div></div>
<div class=two style="margin-top:16px"><div class=box><h3>Doanh thu theo ngày</h3><table>${tb(bd,fmt)}</table><h3 style="margin-top:14px">Doanh thu theo danh mục</h3><table>${tb(bc,fmt)}</table></div><div class=box><h3>Bán chạy trong kỳ</h3><table>${tb(bp,v=>v+' sp')}</table><h3 style="margin-top:14px">Bán chậm</h3><table>${slow.map(p=>`<tr><td>${E(p.name)}</td><td>${p.sold}</td></tr>`).join('')}</table><h3 style="margin-top:14px">Hết hàng / sắp hết</h3><table>${out.map(p=>`<tr><td>${E(p.name)}</td><td>${p.stock?'Còn '+p.stock:'Hết hàng'}</td></tr>`).join('')||'<tr><td>Ổn định</td></tr>'}</table></div></div>`}
function csv(){const[a,b]=statRange(),q=s=>'"'+String(s??'').replace(/"/g,'""')+'"',t='\ufeff'+['Mã đơn,Ngày,Khách,SĐT,Địa chỉ,Thanh toán,Trạng thái,Tổng tiền'].concat(D.orders.filter(o=>o.ts>=a&&o.ts<b).map(o=>[o.id,dt(o.ts),o.name,o.phone,o.addr,o.pay,o.status,o.total].map(q).join(','))).join('\n'),x=document.createElement('a');x.href=URL.createObjectURL(new Blob([t],{type:'text/csv'}));x.download='don-hang.csv';x.click()}
function upImg(i){const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const m=new Image();m.onload=()=>{const k=Math.min(1,600/Math.max(m.width,m.height)),c=document.createElement('canvas');c.width=m.width*k;c.height=m.height*k;c.getContext('2d').drawImage(m,0,0,c.width,c.height);$('#imgv').value=c.toDataURL('image/jpeg',.8);toast('Đã chọn ảnh')};m.src=r.result};r.readAsDataURL(f)}
addEventListener('storage',ev=>{if(ev.key=='lm_db'){load();render()}});if(MODE!='admin')delete R.admin;
addEventListener('hashchange',()=>{render();scrollTo(0,0)});render();
